Modify configure to address hires option compile issue (#1705)
TYPE: bug fix

KEYWORDS: hires, configure, ARCH_LOCAL, CFLAGS_LOCAL, -DRPC_TYPES, landread.o

SOURCE: Mathieu Le Corre, University of Toulouse (France) and University of Brest (France)

DESCRIPTION OF CHANGES:
Problem: When compiling with the vortex-following "hires" option, often a compiling error occurred regarding the landuse.o file.
`mpiicc -DFSEEKO64_OK -o landread.o -c -w -O3 -ip -DDM_PARALLEL -DTERRAIN_AND_LANDUSE -DMAX_HISTORY=25 -DNMM_CORE=0 landread.c
landread.c(130): error: identifier "XDR" is undefined
static XDR *xdrs;
^

landread.c(410): error: identifier "XDR" is undefined
xdrs = (XDR *) malloc(sizeof(XDR));
^

landread.c(410): error: expected an expression
xdrs = (XDR *) malloc(sizeof(XDR));
^

landread.c(410): error: expected a ";"
xdrs = (XDR *) malloc(sizeof(XDR));
^

landread.c(411): error: identifier "XDR_DECODE" is undefined
xdrstdio_create(xdrs, fp, XDR_DECODE);
^

../configure.wrf:404: recipe for target 'landread.o' failed
make[2]: [landread.o] Error 2 (ignored)
`

A similar error was addressed previously in #1072, where -DRPC_TYPES was added to ARCH_LOCAL; however, it needs to be added to CFLAGS_LOCAL, instead.

Solution:
The RPC_TYPES macro is used in landread.c, which is compiled using the .c.o suffix rule in postamble. Accordingly, the definition of RPC_TYPES needs to be included in CFLAGS, and this can be done by adding it to CFLAGS_LOCAL . #1072 included new code in 'configure' to add -DRPC_TYPES to ARCH_LOCAL; however, this need to be put on the CFLAGS_LOCAL, instead. This PR corrects that.

To ensure all configurations will behave properly, it is necessary that each stanza in arch/configure.defaults contains a "#" (or a comment) at the end of the line CFLAGS_LOCAL line. The CYGWIN_NT i686 x86_64 Cygwin, gfortran compiler with gcc stanza was missing it, so configure.defaults has been updated to include the "#" in the CFLAGS_LOCAL line.

LIST OF MODIFIED FILES:
M configure
M arch/configure.defaults

TESTS CONDUCTED:

Modifications fix the problem. Configure, compile, and simulation tested - all successful.
The Jenkins tests are all passing.