TYPE: bug fix
KEYWORDS: El Capitan darwin mac ifort build

SOURCE: Carter Borst (NCAR)

PURPOSE: The Intel compiler under Darwin El Capitan fails in the build (after the compile), with the following type of error: 

time mpif90 -f90=ifort -o wrf.exe  -O3 -ip -fp-model precise -w -ftz -align all -fno-alias -FR -convert big_endian   -ip -Wl,-stack_addr,0xF10000000 -Wl,-stack_size,0x64000000   wrf.o ../main/module_wrf_top.o libwrflib.a /Users/gill/WRF_STUFF/WRFV3/external/fftpack/fftpack5/libfftpack.a /Users/gill/WRF_STUFF/WRFV3/external/io_grib1/libio_grib1.a /Users/gill/WRF_STUFF/WRFV3/external/io_grib_share/libio_grib_share.a /Users/gill/WRF_STUFF/WRFV3/external/io_int/libwrfio_int.a -L/Users/gill/WRF_STUFF/WRFV3/external/esmf_time_f90 -lesmf_time /Users/gill/WRF_STUFF/WRFV3/external/RSL_LITE/librsl_lite.a /Users/gill/WRF_STUFF/WRFV3/frame/module_internal_header_util.o /Users/gill/WRF_STUFF/WRFV3/frame/pack_utils.o  -L/Users/gill/WRF_STUFF/WRFV3/external/io_netcdf -lwrfio_nf -L/usr/local/netcdf-3.6.3-intel/lib  -lnetcdf
Undefined symbols for architecture x86_64:
  "_module_domain_type_mp_program_name_", referenced from:
      _module_wrf_top_mp_wrf_init_ in module_wrf_top.o
      _input_wrf_ in libwrflib.a(input_wrf.o)
      _output_wrf_ in libwrflib.a(output_wrf.o)
ld: symbol(s) not found for architecture x86_64
        6.84 real         1.57 user         0.67 sys
make[1]: [em_wrf] Error 1 (ignored)

Initially, users were trying to go the route of compiling with -fno-commons (which does not work in this case).  I have tried every which way of ordering libraries, using the explicit name.a, moving objects around in the list, etc.  Nothing works except for this flag on ranlib.

DESCRIPTION OF CHANGES: 
In the main directory (literally, "main"), where the executables are put
together from the constituent *.o and *.a files, the ranlib command is modifed
to include the "-c" flag.

Here's the ranlib manpage for the "-c" option:
Include common symbols as definitions with respect to the table of contents.  This is seldom the intended behavior for linking from a library, as it  forces  the  linking  of  a library member just because it uses an uninitialized global that is undefined at that point in the linking.  This option is included only because this was the original behavior of ranlib.  This option is not the default

LIST OF MODIFIED FILES (annotated if not obvious, not required to be on a single line): 
M	main/Makefile

TESTS CONDUCTED (explicitly state mandatory, voluntary, and assigned tests, not required to be on a single line):
1) regression test - do no harm on yellowstone (GNU, PGI, Intel compilers are all OK under Linux)
2) with mod the WRF model builds cleanly with El Capitan + ifort; without the mod the model does not build executables on Darwin with ifort



Index: main/Makefile
===================================================================
--- main/Makefile	(revision 9165)
+++ main/Makefile	(working copy)
@@ -3,6 +3,7 @@
 LN      =       ln -sf
 MAKE    =       make -i -r
 RM      =       rm -f
+RLFLAGS	=	-c
 
 MODULES =  module_wrf_top.F
 
@@ -13,19 +14,19 @@
 include ../configure.wrf
 
 $(SOLVER)_wrf : wrf.o ../main/module_wrf_top.o
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(LD) -o wrf.exe $(LDFLAGS) wrf.o ../main/module_wrf_top.o $(LIBWRFLIB) $(LIB)
 
 $(SOLVER)_wrf_SST_ESMF : wrf_ESMFMod.o wrf_SST_ESMF.o ../main/module_wrf_top.o
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(LD) -o wrf_SST_ESMF.exe $(LDFLAGS) wrf_SST_ESMF.o wrf_ESMFMod.o ../main/module_wrf_top.o $(LIBWRFLIB) $(LIB)
 
 $(SOLVER)_ideal : module_initialize ideal_$(SOLVER).o
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(LD) -o ideal.exe $(LDFLAGS) ideal_$(SOLVER).o ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o $(LIBWRFLIB) $(LIB)
 
 $(SOLVER)_real : module_initialize ndown_$(SOLVER).o nup_$(SOLVER).o tc_$(SOLVER).o real_$(SOLVER).o
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(LD) -o ndown.exe $(LDFLAGS) ndown_$(SOLVER).o  ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o $(LIBWRFLIB) $(LIB)
 	#TEMPORARILY REMOVED $(LD) -o nup.exe $(LDFLAGS) nup_$(SOLVER).o  ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o $(LIBWRFLIB) $(LIB)
 	$(LD) -o tc.exe $(LDFLAGS) tc_$(SOLVER).o  ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o $(LIBWRFLIB) $(LIB)
@@ -32,16 +33,16 @@
 	$(LD) -o real.exe $(LDFLAGS) real_$(SOLVER).o ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o $(LIBWRFLIB) $(LIB)
 
 convert_em : convert_em.o
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(LD) -o convert_em.exe $(LDFLAGS) convert_em.o $(LIBWRFLIB) $(LIB)
 
 convert_nmm : convert_nmm.o
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(FC) -o convert_nmm.exe $(LDFLAGS) convert_nmm.o $(LIBWRFLIB) $(LIB)
 
 real_nmm : real_nmm.o
 	( cd ../dyn_nmm ;  $(MAKE) module_initialize_real.o )
-	$(RANLIB) $(LIBWRFLIB)
+	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 	$(FC) -o real_nmm.exe $(LDFLAGS) real_nmm.o $(LIBWRFLIB) $(LIB)
 
 module_initialize : ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o
@@ -49,7 +50,7 @@
 
 ## prevent real being compiled for OMP -- only for regtesting
 #$(SOLVER)_real : module_initialize real_$(SOLVER).o
-#	$(RANLIB) $(LIBWRFLIB)
+#	$(RANLIB) $(RLFLAGS) $(LIBWRFLIB)
 #	if [ -z "$(OMP)" ] ; then $(FC) -o real.exe $(LDFLAGS) real_$(SOLVER).o ../dyn_$(SOLVER)/module_initialize_$(IDEAL_CASE).o $(LIBWRFLIB) $(LIB) ; fi
 #
 ## prevent module_initialize being compiled for OMP --remove after IBM debugging



git-svn-id: https://svn-wrf-model.cgd.ucar.edu/trunk@9167 b0b5d27b-6f0f-0410-a2a3-cb1e977edc3d